### ISSUE TITLE
"Notebook failed to load" when trying to reopen .ipynb in Jupyter

### ISSUE THREAD

**Issue by egolep** [meatballs/notebook.nvim#10]
Whenever I open a `.ipynb` file inside neovim using this plugin, if I save the file then I'm unable to reopen the notebook correctly inside jupyter and I get the error that I attach below.

![jupyter_error](https://github.com/meatballs/notebook.nvim/assets/71430597/85e4c059-78cb-4807-b7eb-772c753dffa3)

Steps to reproduce: install the plugin, open a `.ipynb` file using it in neovim and save. Then open the file in jupyter

**Comment by egolep** [comment]
Manually adding `"outputs":[]"` to the cell fix it, but re-opening the file with neovim re-breaks everything.

**Comment by meatballs** [comment]
Should be ok now.

**Comment by egolep** [comment]
On code cells, it looks like the problem is solved. But now it gives the "opposite" error in markdown cells (I think this is because markdown cells do not have the `outputs` field)

**Comment by meatballs** [comment]
Try again now

**Comment by egolep** [comment]
It now works perfectly. Thanks!
