### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by egolep** [meatballs/notebook.nvim#6]
This plugin sounds like the final ingredient we needed in order to finally tame jupyter notebooks inside neovim, so I'm very excited about that!
However, I don't understand how to make it works: I tried to install and use it both with `paq-nvim` and `lazy.nvim` but I get no results in both cases: no actual render of the `.ipynb` file (it is opened as the raw `.json`-like format as usual) nor I got the `:NBAddCell` function exported and available.
Am I missing some configuration that is needed in order to make the plugin works? Should I load it explicitly in some way?

**Comment by egolep** [comment]
Yes, I installed the plugin and the files are correctly located in the `paq/start/notebook.nvim` folder.
It looks like the plugin is not loaded, should I add a specific configuration to my `init.lua`?

**Comment by meatballs** [comment]
No, there's no config to do. I don't use paq myself, but my understanding is that you add the location of the repo to you init.lua and then run PaqInstall. More than that, I can't really help, I'm afraid.

**Comment by egolep** [comment]
You tested it with `packer`, right? I'll try to see if I can get the plugin to work using it

**Comment by egolep** [comment]
After some digging, it looks like the plugin is never loaded. If I explicitly import it manually (with `require`) it does work perfectly.
I'm completely new to plugin development, so I don't know if there are some specific ways to solve this problem. Maybe it's an OS specific behavior? I'm on Linux

**Comment by egolep** [comment]
> > After some digging, it looks like the plugin is never loaded. If I explicitly import it manually (with `require` and setting neovim's `rtp`) it does work perfectly. I'm completely new to plugin development, so I don't know if there are some specific ways to solve this problem. Maybe it's an OS specific behavior? I'm on Linux
> 
> I am using [lazy.nvim](https://github.com/folke/lazy.nvim) and also had to do a `require('notebook')`. After that, it works!

I thought I already did that, but now I tried again and it actually works. Strange, maybe I messed up something on my first try.

Thanks @arminveres and obviously thanks to @meatballs!

**Comment by meatballs** [comment]
I'll add a line to the readme when I get a minute. Thanks!

**Comment by egolep** [comment]
To be more specific, I have created a specific `.lua` file (this is probably not, but I usally split my plugin configs by "functionality", which contains:

```lua
return {
    {
      "meatballs/notebook.nvim",
      config = function()
          require("notebook")
      end,
    },
}
```

Hope that helps.
